package com.example.evolvix.data.model

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey
import java.time.LocalDateTime
import com.example.evolvix.ui.theme.HabitColorScheme

/**
 * Database entity representing a habit.
 * Stores all essential information about a habit including progress tracking and appearance.
 *
 * @property id Unique identifier, auto-generated by Room
 * @property name Display name of the habit
 * @property currentCount Current progress towards target
 * @property frequency How often the habit should be performed
 * @property target Goal to reach before considering habit complete
 * @property totalProgressUpdates Total number of progress increments
 * @property totalTargetReaches Number of times target was reached
 * @property lastResetDate When the progress was last reset
 * @property colorScheme Visual theme for the habit
 */
@Entity(tableName = "habits", indices = [Index(value = ["name"], unique = true)])
data class HabitEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val name: String,
    val currentCount: Int,
    val frequency: HabitFrequency = HabitFrequency.Daily,
    val target: Int,
    val totalProgressUpdates: Int = 0,
    val totalTargetReaches: Int = 0,
    val lastResetDate: LocalDateTime = LocalDateTime.now(),
    val colorScheme: HabitColorScheme = HabitColorScheme.GREEN
)