package com.example.evolvix.data.model

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey
import java.time.LocalDateTime

/**
 * Database entity representing a habit.
 * Stores all essential information about a habit including progress tracking and appearance.
 *
 * @property id Unique identifier, auto-generated by Room
 * @property name Display name of the habit
 * @property currentCount Current progress towards target
 * @property frequency How often the habit should be performed
 * @property target Goal to reach before considering habit complete
 * @property totalProgressUpdates Total number of progress increments
 * @property totalTargetReaches Number of times target was reached
 * @property lastResetDate When the progress was last reset
 * @property colorHex Hex color string for the habit (e.g. "#4CAF50")
 * @property categories List of category labels assigned to this habit (e.g. "Health", "Fitness")
 * @property iconKey Optional key identifying the habit's icon; null means auto-resolved
 */
@Entity(tableName = "habits", indices = [Index(value = ["name"], unique = true)])
data class HabitEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val name: String,
    val currentCount: Int,
    val frequency: HabitFrequency = HabitFrequency.Daily,
    val target: Int,
    val totalProgressUpdates: Int = 0,
    val totalTargetReaches: Int = 0,
    val lastResetDate: LocalDateTime = LocalDateTime.now(),
    val colorHex: String = "#4CAF50",
    val categories: List<String> = emptyList(),
    val iconKey: String? = null,
    val reminderEnabled: Boolean = false
)